### ISSUE TITLE
Collaboration with GeoHealth plugin

### ISSUE THREAD

**Issue by Gustry** [ePublicHealth/GeoPublicHealth#1]
Hi, I saw you are maintaining a fork of https://github.com/Gustry/GeoHealth.

We still have some work to do on our repository, but we are going to release a new version soon on plugins.qgis.org (and not in the experimental repository like now).

Do you have some specific needs to maintain in your own fork or do you think we can merge our work together ? Pull requests are more than welcome in the plugin repository. It would be nice if we can collaborate to improve one plugin.

Regards
Etienne

**Comment by mvidaurre** [comment]
Sorry @Gustry to check this until now. Sure I think will be great to collaborate. I'm taking again this project that I left for some time. What do you propose?
