### ISSUE TITLE
Installation fail on windows 10

### ISSUE THREAD

**Issue by raynus** [ePublicHealth/GeoPublicHealth#2]
Plugin installation failed:Failed to unzip the plugin package. Probably it's broken or missing from the repository. You may also want to make sure that you have write permission to the plugin directory: C:/Users/*****/.qgis2/python/plugins

![image](https://user-images.githubusercontent.com/8155495/54882148-b2471600-4e89-11e9-8d93-69536b3fbc60.png)

Python version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.22 Las Palmas, 5a99678469 
OS: Windows 10

#Reproduce steps
1. Run QGIS and install from Plugin-->Manage and Install Plugin
Using epipublichealth repository https://raw.githubusercontent.com/ePublicHealth/GeoPublicHealth/master/plugins.xml 
2. Install GeoPublicHealth plugin

ps Running with Administrator right does not solve the issue.

**Comment by mvidaurre** [comment]
That's now fixed. Thank you for reporting

**Comment by raynus** [comment]
Confirmed, it's now working.

Thanks for the fix :)
