### ISSUE TITLE
Error during Fiona installation

### ISSUE THREAD

**Issue by darbp** [ePublicHealth/GeoPublicHealth#4]
Recently tried to install QGIS. First I installed QGIS Standalone Installer 3.14 (64 bit), then OSGEO4W Network Installer (64 bit). Afterwards, I downloaded a required zip file and extracted it in Windows- SSD (C:). Once this was done the OSGeo4W Shell was ran as administrator and the code "py3_env" was typed in. Then the code "cd .." was typed in twice. Then the code "dir" was typed in .  After this the code "cd installation was typed in (the image labelled as Picture 1 demonstrates this below). Then the command "python3 -m pip install --upgrade pip" was applied and successfully installed (shown under Picture 2). Next is when I plugged in the command for Fiona, which was typed as "pip install Fiona-1.8.13-cp37-cp37m-win_amd64.whl". It tried to install but then an error occurred, which is posted in Picture 3 below.  Picture 4 is a continuation of Picture 3 to help show what occurred.

_Screenshots_
Picture 1: 
![image](https://user-images.githubusercontent.com/78167081/106174708-56273a00-6163-11eb-8390-67ebf3aa5432.png)

Picture 2: 
![image](https://user-images.githubusercontent.com/78167081/106175133-c5049300-6163-11eb-8dda-5d4348713b22.png)

Picture 3: 
![image](https://user-images.githubusercontent.com/78167081/106175632-583dc880-6164-11eb-9643-fa5251a8e091.png)

Picture 4: 
![image](https://user-images.githubusercontent.com/78167081/106175758-7c99a500-6164-11eb-96e7-d687b30ecfcb.png)

_Listed steps of actions_
1. download and installation QGIS Standalone Installer 3.14 (64 bit)
2.  download and installation OSGEO4W Network Installer (64 bit)
3. Downloaded and extracted installation zip file in Windows- SSD (C:)
3. Run OSGEO4W as administrator 
4. typed in  code "cd .. "
5.  repeat step 4 
6. typed in code "dir" 
7. typed in code "cd installation" 
8. typed in code "python3 -m pip install --upgrade pip"
9.  typed in code "pip install Fiona-1.8.13-cp37-cp37m-win_amd64.whl"

**Comment by mvidaurre** [comment]
@raynus could you please check this?

**Comment by raynus** [comment]
Installation (for Windows only)
For windows

Download installation210128.zip(See the repository or this link https://github.com/raynus/GeoPublicHealth/blob/master/installation210128.zip The zip file contains all package in installation folder
Start OSGeo4W Shell as administration
py3_env
CD to installation folder
Then

For QGIS 3.14
pip install Fiona-1.8.13-cp37-cp37m-win_amd64.whl pysal-2.1.0-py3-none-any.whl libpysal-4.2.2.tar.gz

**Comment by mvidaurre** [comment]
Solved on the latest release
