### ISSUE TITLE
Error during Fiona Installation

### ISSUE THREAD

**Issue by weondong** [ePublicHealth/GeoPublicHealth#5]
Dr. Najera and I were having trouble with GIS installation where there was no GDAL installed and gave us an error code we could not figure out. It is down below, occurred when trying to input the code "pip install Fiona-1.8.13-cp37-cp37m-win_amd64.whl"

ERROR: Command errored out with exit status 1: 'c:\osgeo4~1\bin\python3.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\weond\\AppData\\Local\\Temp\\pip-install-ei5utyz9\\gdal_cab93a3c000e4960b28370b93113edab\\setup.py'"'"'; __file__='"'"'C:\\Users\\weond\\AppData\\Local\\Temp\\pip-install-ei5utyz9\\gdal_cab93a3c000e4960b28370b93113edab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\weond\AppData\Local\Temp\pip-record-8ncxd8ms\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\OSGEO4~1\apps\Python37\Include\gdal' Check the logs for full command output.

**Comment by mvidaurre** [comment]
Solved on the latest release
