### ISSUE TITLE
Couldn't load plugin 'GeoPublicHealth' ModuleNotFoundError: No module named 'pysal'l' 

### ISSUE THREAD

**Issue by hasiet2020** [ePublicHealth/GeoPublicHealth#9]
I use windows and tried to install GeoPublicHealth plugin based on the following procedure
Installing GeoPublicHealth Plugin
Start QGIS and launch the plugins manager by going to the Plugins menu and selecting Manage and Install Plugins….
In the Settings tab of the plugins settings dialog, scroll down and click on the Add… button.
Give the plugin repository the name epipublichealth and then add the full URL https://raw.githubusercontent.com/ePublicHealth/GeoPublicHealth/main/docs/plugins.xml in the URL field.
Please be sure that Show also experimental plugins is checked [x]
Click on the OK button.
Activate the All tab and Search field input geopu.
Select the GeoPublicHealth plugin
Click on the Install plugin button
Close the Plugins dialog
Check in the Plugins menu that the GeoPublicHealth plugin is a new option there

 and recieved the following error message
Couldn't load plugin 'GeoPublicHealth' ModuleNotFoundError: No module named 'pysal'l'

**Comment by mvidaurre** [comment]
Solved with the new QGIS release
